### ISSUE TITLE
Implement the required zk-proofs for the Covid passport use case 

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2124]
Tasks:

- [x] write zk-proofs Rust code
  - [x] Daniel work on set membership zkp (can be used to prove a vaccine product id was given)
  - [x] Simple boolean attribute proofs with random number from verifier
- [x] test integration with existing Coconut code in https://github.com/nymtech/nym/blob/develop/clients/tauri-client/src-tauri/src/main.rs#L111-L158

### Stage 1

Needs to be able to prove:

- `is_vaccinated: boolean`
- `is_over_18: boolean`
- `is_over_21: boolean`

And private attributes:

- `encrypted_secret: byte[]` - a secret on the user phone, can decrypt to prove they requested the creation of this credential

The phone app will check the user's age before responding to a verifier in case it has changed (e.g. they were 17 when the credential was issued and now they are 18 - in this case a new credential needs to be issued that would contain `is_over_18 = true`).

### Stage 2

And reveal the following in clear text:

- user's full name as a `string`
- user's date of birth as a `string` in format `YYYY-MM-DD`
- the vaccine product as a `string` (it will contain the medication product identifier which is unique, e.g. `EU/1/20/1507` = "COVID-19 Vaccine Moderna")

The Coconut credential will have the following public attributes:

- `patient_id: string` (e.g. NHS No, identity number, social security no, etc)
- `full_name: string`
- `vaccine_medication_product_id: string` - e.g. the value will be `EU/1/20/1528` (https://github.com/ehn-dcc-development/ehn-dcc-vsu/blob/3319161c8bc93032a9f7d45c71bf363b8b567d83/server/static/vaccine-medicinal-product.json)
- `country_of_vaccination: string` - https://en.wikipedia.org/wiki/ISO_3166-1 two letter code e.g. `gb`, `fr`, `it`, `nl`, `gr` (https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/release/2.2.0/country-2-codes.json)
- `issuer: string` (e.g NHS, Public Health England, etc) - an URN for each country
- `dob`: string (`YYYY-MM-DD` format)
- `is_vaccinated: boolean`
- `is_over_18: boolean`
- `is_over_21: boolean`

Value sets can be found in https://github.com/ehn-dcc-development/ehn-dcc-valuesets.

**Comment by mmsinclair** [comment]
@aniampio George suggests we use booleans to make the proof trivial for age checks, instead of messing around with dates
