### ISSUE TITLE
Finish UI Webdriverio tests for Nymtech.net

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#2577]
**Description**
To provide quick feedback on the UI of Nyms website - UI test pack to cover:

- Validation of links / Redirects
- Screen components
- Translations

**Tasks**
- [x] Baseline of test framework / POM design
- [ ] Finish off test cases 
- [ ] Run against a variation of drivers in a hub in CI (Firefox, Chrome, Edge) 

**Definition of done**

Tests running on CI once triggered on a respective branch for the website

**Comment by tommyv1987** [comment]
Moving back to cold storage temporarily as other things are in the pipeline. Work is mostly complete.

**Comment by roughprada** [comment]
@tommyv1987 / @jessgess Moving this story to GL: https://gitlab.nymte.ch/nym/nym-websites/-/issues/26
