### ISSUE TITLE
QA - Finish off webdriverio tests for nym_wallet

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#2578]
**Description**
To provide quick feedback on the UI components of the nym_wallet, a small E2E, UI regression suite will cover the happy paths of the app.

**Tasks**

- [x] Baseline of test framework
- [x] Execute tests dependant on suite (existing user / non existing user) - configurable in the `wdio.config.js`
- [x] Refactor old selectors and add reporting
- [x] For existing user - keep user credentials in secrets manager
- [x] Finalise CI jobs (if we want to run on windows, configuration will differ from a unix agent)
- [x] Change to Typescript?

**Definition of done**

Tests running on CI once triggered on a respective branch for the wallet, clear instructions to run the suite.

**Comment by tommyv1987** [comment]
Project is now running in Github Actions, no action required to change to TS for the time being.

Minor config needs to change on GHA.

**Comment by tommyv1987** [comment]
Moving to done will raise a small subtask to sweep up the residual code, and github actions.
