### ISSUE TITLE
[Meta task] Minimal mixnet VPN PoC

### ISSUE THREAD

**Issue by octol** [nymtech/nym#3936]
# Nym VPN minimal mixnet CLI PoC

Minimal mixnet VPN PoC. Basically consisting of two components

- A simple CLI client that captures all local IP traffic and sends it over the mixnet
- IP packet routing on the exit gateway

The client optionally supports connecting to the entry gateway using wireguard

This is the meta task that keeps track of all the subtasks.

## Tasks

- [x] #3725
- [x] #3869
- [x] #3903
- [x] #3937
- [x] #3987
- [x] #3991
- [x] #3938
- [x] #3990
- [x] #3939
- [x] #4129 
- [x] #4179
- [x] #4178
- [x] #4184
- [x] #4185
- [x] #4130 
- [x] Disable poisson rate in client
- [x] Add flag for MTU
- [x] #4219
- [x] #4218
- [x] #4259
- [ ] Sign connect requests to stop DoS loophole
- [x] Switch to `10.0.0.0/16` to allow for more than 254 clients per exit gateway.
- [ ] Make IP allocation smarter and not give up before all are allocated.
- [x] Backpressure in client
- [x] Backpressure in nym-ip-packet-router
- [ ] Client disconnect request, to free up IP addresses.
- [x] Allow the  nym-ip-packet-router to run separately from the exit gateway
- [x] Support running IPR and NR simultaneously

## Bugs

- [x] Restore routing table on Linux fails when not in wireguard mode
- [x] Throughput appears to be asymmtric
- [x] IPv6 is not captured
