### ISSUE TITLE
Implement nym-explorer automation tests

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#858]
**Description**
To provide quick feedback on the UI of the new nym-network explorer

**Definition of ready**
- Network explorer to be consumed in test environment
- Test cases to be defined
- Data Id's to be added

**Tasks**

- [] Baseline of test framework - using `webdriverio`
- [] Add id's`"[data-testid='test']"` to the React app - use these explicitly to define and use elements on the page
- [] If necessary store files in secrets if applicable in GH actions
- [] Finalise CI jobs (use webdriver service and run concurrently on various browsers (firefox, edge, chrome, safari))
- [] 50/50 - Based upon the point above, gather a user browser matrix?

**Definition of done**

Tests running on CI once triggered on a respective branch for the network explorer, clear instructions to run the suite

**Comment by tommyv1987** [comment]
@Aid19801 does the criteria above look good to you?
